export const AVERAGE_MEASUREMENTS_REQUEST = "AVERAGE_MEASUREMENTS_REQUEST";
export const AVERAGE_MEASUREMENTS_SUCCESS = "AVERAGE_MEASUREMENTS_SUCCESS";
export const AVERAGE_MEASUREMENTS_FAILURE = "AVERAGE_MEASUREMENTS_FAILURE";
export const LOAD_MEASUREMENT_REQUEST = "LOAD_MEASUREMENT_REQUEST";
export const LOAD_MEASUREMENT_SUCCESS = "LOAD_MEASUREMENT_SUCCESS";
export const LOAD_MEASUREMENT_FAILURE = "LOAD_MEASUREMENT_FAILURE";
